// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjp4Xj3LFCGMBL9glv-qvYX7TMSABLDCE',
    appId: '1:470573374022:android:0cc30377c4af30fedf0847',
    messagingSenderId: '470573374022',
    projectId: 'noteify-90951',
    storageBucket: 'noteify-90951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuNdCHfH6epEK_e2auYqWIoXJc6m6lfFE',
    appId: '1:470573374022:ios:e6dee36e9f6d8e33df0847',
    messagingSenderId: '470573374022',
    projectId: 'noteify-90951',
    storageBucket: 'noteify-90951.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtHQppi7u33WkNVTtGjWcNKE-g7RYVcPo',
    appId: '1:470573374022:web:b25761daf28e9b07df0847',
    messagingSenderId: '470573374022',
    projectId: 'noteify-90951',
    authDomain: 'noteify-90951.firebaseapp.com',
    storageBucket: 'noteify-90951.firebasestorage.app',
    measurementId: 'G-PZQLJJ4YTR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuNdCHfH6epEK_e2auYqWIoXJc6m6lfFE',
    appId: '1:470573374022:ios:e6dee36e9f6d8e33df0847',
    messagingSenderId: '470573374022',
    projectId: 'noteify-90951',
    storageBucket: 'noteify-90951.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtHQppi7u33WkNVTtGjWcNKE-g7RYVcPo',
    appId: '1:470573374022:web:488d5e322003792cdf0847',
    messagingSenderId: '470573374022',
    projectId: 'noteify-90951',
    authDomain: 'noteify-90951.firebaseapp.com',
    storageBucket: 'noteify-90951.firebasestorage.app',
    measurementId: 'G-XZXKRR69PR',
  );

}